// Only countries supported by the Nager.Date API (date.nager.at/api/v3/AvailableCountries).
// CN, RU, SA, AE, EG, PK, BD are not in Nager's dataset — including them caused
// every per-country request to 404, return [], and cache that empty result for 1 year.
export const COUNTRIES_TO_FETCH = [
  'UA',
  'US',
  'GB',
  'DE',
  'FR',
  'CA',
  'AU',
  'JP',
  'IN',
  'BR',
  'MX',
  'AR',
  'ZA',
  'PL',
  'IT',
  'ES',
  'NL',
  'BE',
  'SE',
  'NO',
  'DK',
  'FI',
  'CH',
  'AT',
  'IE',
  'PT',
  'GR',
  'KR',
  'SG',
  'MY',
  'TH',
  'NZ',
  'TR',
  'VN',
  'PH',
];
